export const MOUSE_REPEL_DEFAULTS = {
  dotCount: 500,
  repelRadius: 200,
  force: 5.5,
  springK: 0.05,
  damping: 0.80,
  minDotSize: 0.6,
  maxDotSize: 9,
  dotColor: '#ffffff',
  dotColorMid: '#d35af8',
  dotColorHot: '#ffffff',
};

export const MOUSE_REPEL_PARAM_META = [
  {
    key: 'dotCount',
    label: 'dotCount',
    type: 'number',
    min: 50,
    max: 500,
    step: 10,
    scrollStep: 10,
  },
  {
    key: 'repelRadius',
    label: 'repelRadius',
    type: 'number',
    min: 20,
    max: 200,
    step: 5,
    scrollStep: 5,
  },
  {
    key: 'force',
    label: 'force',
    type: 'number',
    min: 0.5,
    max: 10,
    step: 0.1,
    scrollStep: 0.1,
    decimals: 1,
  },
  {
    key: 'springK',
    label: 'springK',
    type: 'number',
    min: 0.01,
    max: 0.3,
    step: 0.01,
    scrollStep: 0.01,
    decimals: 2,
  },
  {
    key: 'damping',
    label: 'damping',
    type: 'number',
    min: 0.3,
    max: 0.98,
    step: 0.01,
    scrollStep: 0.01,
    decimals: 2,
  },
  {
    key: 'minDotSize',
    label: 'minDotSize',
    type: 'number',
    min: 0.5,
    max: 10,
    step: 0.1,
    scrollStep: 0.1,
    decimals: 1,
  },
  {
    key: 'maxDotSize',
    label: 'maxDotSize',
    type: 'number',
    min: 0.5,
    max: 20,
    step: 0.1,
    scrollStep: 0.1,
    decimals: 1,
  },
  {
    key: 'dotColor',
    label: 'dotColor',
    type: 'color',
  },
  {
    key: 'dotColorMid',
    label: 'dotColorMid',
    type: 'color',
  },
  {
    key: 'dotColorHot',
    label: 'dotColorHot',
    type: 'color',
  },
];
